[package]
name = "bart_info"
version = "0.1.0"
authors = ["Ebrahim Azarisooreh <ebrahim.azarisooreh@gmail.com>"]
edition = "2018"

[dependencies]
alexa_sdk = "0.1.3"
lambda_runtime = "0.2.0"

[[bin]]
name = "bootstrap"
path = "src/main.rs"
